// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7uBrm-rL3L9znvV15aNplpvT9xNoR1hc',
    appId: '1:1000248031102:web:69f8b0b2f7e31c8630e52f',
    messagingSenderId: '1000248031102',
    projectId: 'appfood-35e70',
    authDomain: 'appfood-35e70.firebaseapp.com',
    storageBucket: 'appfood-35e70.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGq39jaT5fu2UAg8Zyl-0ZcMnFdmSynTs',
    appId: '1:1000248031102:android:b3ee5462ec72162130e52f',
    messagingSenderId: '1000248031102',
    projectId: 'appfood-35e70',
    storageBucket: 'appfood-35e70.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCVj9ipaj0xZJNDjFLjwNhKK7HvCjEXSo',
    appId: '1:1000248031102:ios:d1f37628ad9957d730e52f',
    messagingSenderId: '1000248031102',
    projectId: 'appfood-35e70',
    storageBucket: 'appfood-35e70.appspot.com',
    iosBundleId: 'com.kds.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCVj9ipaj0xZJNDjFLjwNhKK7HvCjEXSo',
    appId: '1:1000248031102:ios:f56aee7b463fcb0230e52f',
    messagingSenderId: '1000248031102',
    projectId: 'appfood-35e70',
    storageBucket: 'appfood-35e70.appspot.com',
    iosBundleId: 'com.kds.foodApp.RunnerTests',
  );
}
